# ansi.yml
---
- name: Install Docker on EC2 instance
  hosts: [webservers]
  become: yes
  gather_facts: yes

  vars:
    docker_release: "jammy"  # Force use of Ubuntu 22.04 repo even on newer systems like 24.04

  tasks:
    - name: Update apt package cache
      ansible.builtin.apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600

    - name: Install necessary packages for Docker
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present

    - name: Ensure /etc/apt/keyrings directory exists
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Add Docker's official GPG key to new location
      ansible.builtin.shell:
        cmd: "curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg"
        creates: /etc/apt/keyrings/docker.gpg

    - name: Ensure correct permissions for Docker GPG key
      ansible.builtin.file:
        path: /etc/apt/keyrings/docker.gpg
        mode: '0644'

    - name: Set up the stable Docker repository
      ansible.builtin.apt_repository:
        repo: "deb [arch={{ ansible_facts['architecture'] }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ docker_release }} stable"
        state: present
        filename: docker

    - name: Update apt cache after adding Docker repo
      ansible.builtin.apt:
        update_cache: yes
        force_apt_get: yes

    - name: Install Docker using official convenience script
      ansible.builtin.shell: |
        curl -fsSL https://get.docker.com -o get-docker.sh
        sh get-docker.sh
      args:
        creates: /usr/bin/docker

    - name: Add current user to docker group
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Restart Docker service
      ansible.builtin.service:
        name: docker
        state: restarted
        enabled: yes

    - name: Verify Docker installation
      ansible.builtin.command: docker run hello-world
      register: docker_hello_world_result
      changed_when: false

    - name: Print Docker Hello World result
      ansible.builtin.debug:
        msg: "{{ docker_hello_world_result.stdout }}"
